# Generated by Django 3.2.6 on 2021-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=60)),
                ('cargo', models.CharField(max_length=60)),
                ('unidad', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Datos del Solicitante',
            },
        ),
    ]
