# Generated by Django 3.2.6 on 2021-08-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solicitante', '0001_initial'),
        ('Dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigo_de_inventario', models.CharField(max_length=60)),
                ('descripcion_del_problema', models.TextField()),
                ('detalles_del_equipo', models.TextField()),
                ('receptor', models.CharField(max_length=60)),
                ('autorizado', models.CharField(max_length=60)),
                ('revisado_por', models.CharField(max_length=60)),
                ('detalle_tecnico_del_problema', models.TextField()),
                ('descripcion_de_la_solucion', models.TextField()),
                ('materiales_utilizados', models.TextField()),
                ('herramientas_utilizadas', models.TextField()),
                ('tipos_de_servicio', models.TextField()),
                ('entregado_por', models.CharField(max_length=60)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solicitante.solicitantes')),
                ('tipo_de_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Trabajo',
            },
        ),
    ]
