# Generated by Django 3.2.6 on 2021-08-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='aprobado_por',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
