# Generated by Django 3.2.6 on 2021-08-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0003_alter_orden_codigo_de_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='numero',
            field=models.CharField(default='GADMED-UIT-2021', max_length=60),
        ),
    ]
