# Generated by Django 3.2.6 on 2021-08-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0004_orden_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
