# Generated by Django 3.2.6 on 2021-08-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0005_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
